### ISSUE TITLE
Edits in the prioritisation spider chart (chart 3)

### ISSUE THREAD

**Issue by guizar** [Vizzuality/half-earth#154]
Updates requested:
1. Remove blue layer
2. Tooltip suggestions:
	- Change "Percentage" to "%"
	- Decrease rounding to 2 decimals (00.00)
3. Remove "All" axis
4. Change legends to  "% species meeting conservation target"

<img width="506" alt="screen shot 2017-10-21 at 19 17 59" src="https://user-images.githubusercontent.com/7090413/31859560-7e66ce1a-b705-11e7-9bdd-4ef3e25e7f19.png">

**Comment by jmalczyk** [comment]
The percent protected currently (blue) is actually correct -- the reason we see the discrepancy reported by Walter is because the slider is starting at 15%. Global terrestrial reserve coverage using our 'all' classification is actually closer of 12.4 %. Lots of species gain protected status moving the slider from the 12% scenario to 15% under our prioritization framework. If you can start the slider lower, this will work as intended (initially all blue, then growing outward as species are added).

**Comment by jmalczyk** [comment]
This tool should also trigger map tiles to show at 15%. Currently they only come on once you bump it to 16%. Also the blue area is correct when the slider is pushed all the way left (15%) but shrinks incorrectly when slide up beyond. If values for current protection have been hard-coded, check the API again, as those values have been updated to reflect the recent inclusion of marine areas (which often run up onto land or across coastal areas).

**Comment by jmalczyk** [comment]
I just checked this again and the feature seems to have regressed. Moving the slider should always result in the spider values moving outward (higher). The values never go down as the scenario increases. As of right now (7:30 AM EST) the spider values jump up and down as the slider moves toward 50%. If this cant be fixed before demo time that chart needs to be pulled out.

**Comment by jmalczyk** [comment]
Also, just to confirm -- the correct API is being used
https://storage.googleapis.com/cdn.mol.org/half-earth/data/reserve-coverage/all-taxa.json
This chart should be drawing percentSpeciesMeetingTargetProtectedAreaViaAny starting from scenario 15 for each taxa.

**Comment by simaob** [comment]
Hi Jeremy, regarding the jumpiness this is related to the fact that the data is normalized for each level, so when moving the slider if there’s data that goes over the range for the previous displayed level, the chart is adjusted. We are looking to normalize it to the whole set instead, so that it’s progressive, and not jumping around.

**Comment by guizar** [comment]
The `radar` module normalises the visualisation scales at each slider step. This behaviour became more apparent when removing the `percentProtectedCurrent` layer. If this cannot be adapted then a new type of figure will have to be introduced

**Comment by vectorsize** [comment]
If we want to resove this pragmatically we should replace the spider with a Barchart, as suggested several times.

**Comment by guizar** [comment]
👍  let's do that @vectorsize  @sorodrigo

**Comment by jmalczyk** [comment]
Agreed. Bar chart is probably more intuitive anyway.

**Comment by arimariza** [comment]
check this out:
[https://www.dropbox.com/s/k68eiouobvkuoua/bar_chart.png?dl=0](url)

**Comment by jmalczyk** [comment]
Much better. That also should work better on smaller screens.

**Comment by guizar** [comment]
Spiderchart replaced with a barchart (currently in staging), works much better now!
